command:
- ${interpreter}
- ${program}
- --output_per_relation_scores
- --test
- ${args}
name: MRN_inference
program: src/prob_cbr/pr_cbr.py
method: bayes
metric:
  goal: maximize
  name: hits_10
parameters:
  dataset_name:
    value: "MRN_ind"
  data_dir:
    value: "/mnt/nfs/home/rajarshi/Dropbox/research/drug_repurposing_prob_cbr/"
  num_paths_around_entities:
    value: 5000
  max_num_programs:
    min: 4
    max: 250
  k_adj:
    min: 2
    max: 50
  linkage:
    value: 0.0
  use_path_counts:
    value: 1
  aggr_type1:
    values:
      - "none"
      - "sum"
  aggr_type2:
    values:
      - "sum"
      - "max"
      - "logsumexp"
  use_wandb:
    value: 1