command:
- ${interpreter}
- ${program}
- --test
- --output_per_relation_scores
- ${args}
project: pr-cbr
name: OBL-test
program: src/prob_cbr/pr_cbr.py
method: grid
metric:
  goal: maximize
  name: hits_10
parameters:
  dataset_name:
    value: "obl2021"
  data_dir:
    value: "/mnt/nfs/work1/mccallum/rajarshi/Dropbox/research/Open-BIo-Link/"
  linkage:
    value: 0
  use_path_counts:
    value: 1
  per_relation_config_file:
    value: "sweep_21j6vk1m_best_per_rel_config.json"
  num_paths_around_entities:
    value: 5000
  input_file_name:
    values: ['711_test.txt', '789_test.txt', '802_test.txt', '749_test.txt', '706_test.txt']
  use_wandb:
    value: 1